# Generated by Django 3.2 on 2022-02-16 15:37

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
