# Generated by Django 3.2 on 2022-02-16 15:52

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
